### ISSUE TITLE
Text overlays itself in the Library

### ISSUE THREAD

**Issue by TheDarocker** [HorizonLauncher/Client#15]
![Image](https://i.gyazo.com/e8fc672a1371e6af7773aa33fe74e02b.png)

As you can see, the "Steam" (for identifying the DRM) is cut out by the title of the game and so is the hour count, with "Played".

Minor detail bug. Only occurs on the library page.

**Comment by thomassross** [comment]
Confirmed on Linux as well

**Comment by TheDarocker** [comment]
Due to this library view being scratched and replaced with the grid view in ed37a69aa5ed93a8c9ee627561afd0d8cd9cb558, this issue no longer applies.
