### ISSUE TITLE
Add Mozilla Persona

### ISSUE THREAD

**Issue by pizzamaker** [HorizonLauncher/Client#16]
Facebook and Google for signing up is a problem for many, since they are well-known privacy violators.

Please add the Mozilla Persona authentication system: https://developer.mozilla.org/en-US/Persona

**Comment by thomassross** [comment]
Hi,

This is more of a backend issue (which you can discuss in `#backend` on our slack), but we are planning on having these options:
- Horizon Account
- Google Account
- Mozilla Persona
- Steam

**Comment by pizzamaker** [comment]
Nice! Thanks.
