### ISSUE TITLE
Folders in DRM Wizard are lowercase and use the wrong Slash

### ISSUE THREAD

**Issue by TheDarocker** [HorizonLauncher/Client#21]
![Image](https://i.gyazo.com/c082ccfea42433a9b2138cc94fd578a9.png)

It's just a small detail bug that's bothering me- it should be "C:\Program Files (x86)\Steam" not "C:/program files (x86)/steam". Wrong type of Slash (should be \, not /) and they're lowercase.

**Comment by thomassross** [comment]
Seems like it's Steam's fault - Steam is storing the lowercase path in the registry.

**Comment by thomassross** [comment]
Not sure why GitHub closed this..

**Comment by thomassross** [comment]
Closed with #28
