### ISSUE TITLE
DRM wizard does not add games sometimes

### ISSUE THREAD

**Issue by thomassross** [HorizonLauncher/Client#29]
Steps to reproduce:
1. Add some games the the database
2. Clear the database
3. Run the DRM wizard
4. Library doesn't refresh

**Comment by TheDarocker** [comment]
Reproduced on Windows 7

**Comment by thomassross** [comment]
Also happens when removing a game, and then re-adding it. Seems to be a problem with `Database::addGame`

**Comment by thomassross** [comment]
Also looks like it does not fix when re-launching the client and trying to re-add.
