### ISSUE TITLE
Thin black bar appearing under the title bar of all wizard windows

### ISSUE THREAD

**Issue by TheDarocker** [HorizonLauncher/Client#31]
![Image1](https://i.gyazo.com/6954239d400a7d739d46f513d4a810d2.gif)
![Image2](https://i.gyazo.com/d378bca7b8bb7db7c0e53e7d7e6a4e90.png)

Disappears on rebuild, appears when you go to the next tab of the wizard or alt-tab/go to another program and then come back. Found on Windows, not sure if it will appear on other systems.

**Comment by thomassross** [comment]
Can not reproduce on Windows 7 (64-bit)
