### ISSUE TITLE
Library: Carousel view

### ISSUE THREAD

**Issue by thomassross** [HorizonLauncher/Client#35]
![library-carousel](https://cloud.githubusercontent.com/assets/3471434/11604470/f22a92dc-9aba-11e5-8244-0cc042bbfa08.png)

(#17)

**Comment by TheDarocker** [comment]
Quick note: In this mockup the selected library view icon is on the wrong icon. It should not be selected on the grid icon, it should be on the last icon (the list icon).

Will try to change ASAP- pinging @BreadRex

**Comment by thomassross** [comment]
Fixed.

**Comment by thomassross** [comment]
Fixed in 1bc7ef5
