### ISSUE TITLE
On maximization/minimization, settings window button disappears until hover

### ISSUE THREAD

**Issue by TheDarocker** [HorizonLauncher/Client#62]
When you maximize/minimize a window, the settings button will disappear until you hover over it again. This applies to when you go from maximized to minimized and when you go to minimized to maximized. Found on elementary OS (Ubuntu) 0.3.2.

![Image1](https://i.gyazo.com/068c6a1c46a01f66839abb1302b41052.png)
![Image2](https://i.gyazo.com/ec626bfa3efbda8461d8d8356866ca54.png)

**Comment by Micklas422** [comment]
Can reproduce on Elementary OS 0.3.2

**Comment by thomassross** [comment]
Can no longer reproduce... Can anyone else try again?

Cc: @TheDarocker @MySelfLuls

**Comment by thomassross** [comment]
> @thomasross: Yup, can confirm as non-reproducible now. Also an icon error with the maximize/minimize button has now been fixed, it seems.
> - @TheDarocker
