### ISSUE TITLE
Add default/pre-added news feeds

### ISSUE THREAD

**Issue by TheDarocker** [HorizonLauncher/Client#65]

**Comment by BurrrY** [comment]
Which one do we want?
/r/gamernews, /r/pcmr, /r/gaming?

**Comment by TheDarocker** [comment]
@BurrrY [Non-final list of different gaming news websites here.](https://docs.google.com/document/d/1XaDzdw1btklmgARTmnbTxVJ8J6xFFjTOPB7Q_IretPo/edit)

Not sure what subreddits we should do, but I think we should stay away from /r/PCMasterRace as a default.

**Comment by DarvishKamalia** [comment]
/r/pcgaming would be better imo
