### ISSUE TITLE
DRM Wizard crash

### ISSUE THREAD

**Issue by thomassross** [HorizonLauncher/Client#7]
If no DRMs are installed on the system, the wizard will detect both Steam and Origin in `.`, and then crash.

![Wizard](http://i.imgur.com/0mc9dFx.png)

**Comment by TheDarocker** [comment]
![Image](https://i.gyazo.com/1cce6c539099885d4552b502c5a713e4.png)

If Origin is not installed/no games are present, it shows CMakeFiles.txt as a potential game.
