### ISSUE TITLE
Linux compiling fails: c++: internal compiler error: Killed (program cc1plus)

### ISSUE THREAD

**Issue by PureTryOut** [HorizonLauncher/Client#73]
After a short tedious search for what Qt5 dependencies I actually needed (please fix this on the compiling page) instead of the whole lot, compiling fails at 90% with the error
`c++: internal compiler error: Killed (program cc1plus)`.

Even though Arch reports that this should be reported to the Arch developers, it only happens with this application so it seems more fitting for me to report it here. 

Full error:

```
c++: internal compiler error: Killed (program cc1plus)
Please submit a full bug report,
with preprocessed source if appropriate.
See <https://bugs.archlinux.org/> for instructions.
CMakeFiles/HorizonLauncher.dir/build.make:846: recipe for target 'CMakeFiles/HorizonLauncher.dir/qrc_Fonts.cpp.o' failed
make[2]: *** [CMakeFiles/HorizonLauncher.dir/qrc_Fonts.cpp.o] Error 4
CMakeFiles/Makefile2:67: recipe for target 'CMakeFiles/HorizonLauncher.dir/all' failed
make[1]: *** [CMakeFiles/HorizonLauncher.dir/all] Error 2
Makefile:83: recipe for target 'all' failed
make: *** [all] Error 2
```

**Comment by PureTryOut** [comment]
Never mind, fixed it by running the make command listed instead of just `make`. Still, would like to see specified which specific parts of Qt5 are required.

**Comment by thomassross** [comment]
Hi, this simply means that the compiler was killed for some reason (probably ran out of memory or something similar.)

I will add a list of Qt5 dependencies on the compiling page.

Thanks.

**Comment by thomassross** [comment]
I've updated the docs including your suggestions.

**Comment by PureTryOut** [comment]
Thanks! I'll look into making an AUR package for this now, would be my first ;)
