### ISSUE TITLE
Names on the friendlist don't have a style set.

### ISSUE THREAD

**Issue by BMaxV** [HorizonLauncher/Client#77]
They're black on very dark grey. You can change the grey but no the black in the settings since the black is probably the default that doesn't get overridden.

This should be easy and I think I already have a fix, I just need to build, confirm that it works, then I'll make a pull request.

**Comment by thomassross** [comment]
Hi,

The friends list and community pages have not been implemented fully yet, the current design is just a placeholder for when we actually start to work on that part of the client.
