### ISSUE TITLE
reserved identifier violation

### ISSUE THREAD

**Issue by elfring** [HorizonLauncher/Client#78]
I would like to point out that identifiers like "[`_STORE_H_`](https://github.com/HorizonLauncher/Client/blob/ab6ecc89f7719cb51262b56dc0fbcd79f84ff0f1/Source/Store.h#L1)" and "[`_TABWIDGET_H_`](https://github.com/HorizonLauncher/Client/blob/1eab218340f36fbe474e6031d2db26e2fdb71c83/Source/TabWidget.h#L1)" [do not fit](https://www.securecoding.cert.org/confluence/display/cplusplus/DCL51-CPP.+Do+not+declare+or+define+a+reserved+identifier#DCL51-CPP.Donotdeclareordefineareservedidentifier-NoncompliantCodeExample%28HeaderGuard%29) to the expected naming convention of the C++ language standard.
Would you like to adjust your selection for unique names?

**Comment by TheDarocker** [comment]
Good catch! If you'd like- since this a small low priority issue- can you make the changes and PR?

**Comment by thomassross** [comment]
Fixed. Thanks

**Comment by elfring** [comment]
Thanks for [your improvement of affected include guards](https://github.com/HorizonLauncher/Client/commit/bf59cbb9f067bbe0a27f7a8fa40611ae998ccdb5).
