### ISSUE TITLE
Catch exceptions in main()?

### ISSUE THREAD

**Issue by elfring** [HorizonLauncher/Client#79]
I expect that exception handling is usually supported by a C++ program. I wonder why your function "[main](https://github.com/HorizonLauncher/Client/blob/391f9afa3a8ae728bfab10cc2abb91910544f6e5/Source/Main.cpp#L24)" does not contain [corresponding try and catch instructions](http://stackoverflow.com/questions/368184/does-it-make-sense-to-catch-exceptions-in-the-main) so far.

How do you think about recommendations by Matthew Wilson in [an article](http://accu.org/index.php/journals/1706)?

Would you like to adjust the implementation if you consider [effects for uncaught/unhandled exceptions](http://www.informit.com/guides/content.aspx?g=cplusplus&seqNum=108) like they are described by Danny Kalev?

**Comment by thomassross** [comment]
I'm not sure what you're asking.

Are you trying to say we should be catching every exception by wrapping our main function with this:

```
try
{
    // code
}
catch (std::exception& exc)
{
}
```

?

**Comment by elfring** [comment]
Yes. - [A catch-all clause](http://en.cppreference.com/w/cpp/language/try_catch) might be also useful.

Would you like to [reconsider consequences from implementation-defined behaviour](http://stackoverflow.com/questions/5557555/raii-and-stack-unwinding)?

**Comment by elfring** [comment]
Thanks for [your small source code improvement](https://github.com/HorizonLauncher/Client/commit/d3114a2c357403c5f96341687a16b1efa7c6001d).

How do you think about to use also the constructs "`catch (std::bad_alloc const & ba)`" and "`catch (...)`"?
