### ISSUE TITLE
QtWebKit is deprecated in Qt 5.5+

### ISSUE THREAD

**Issue by TheDarocker** [HorizonLauncher/Client#81]
Issues currently arising where `QtWebKit` and `QtWebKitWidgets` are not installed and therefore cause the client to not compile are caused by the [deprecation of QtWebKit](https://wiki.qt.io/New-Features-in-Qt-5.5#Deprecated_Functionality).

`QtWebKit` is used by the store tab to display the page, but according to this [porting guide](https://doc-snapshots.qt.io/qt5-5.6/qtwebenginewidgets-qtwebkitportingguide.html) it should be an easy fix.

**Comment by thomassross** [comment]
There are no official Ubuntu or Debian packages for QWebEngine yet so we will have to stay on <= Qt 5.5.
