### ISSUE TITLE
Icons need to be changed to Google's Material Icons for the DFSG

### ISSUE THREAD

**Issue by TheDarocker** [HorizonLauncher/Client#88]
We need to abide by the DFSG in order to be able to publish on the Debian repositories, and prevents potential trouble in the future with other distribution repositories.

**Comment by TheDarocker** [comment]
Icons added in 2c14550

**Comment by TheDarocker** [comment]
Icons need to be implemented, of course

**Comment by thomassross** [comment]
@TheDarocker please add https://design.google.com/icons/#ic_delete
